"""bookings

Revision ID: c2f269907d48
Revises: 69091c1537d3
Create Date: 2026-05-23 00:27:53.052888

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c2f269907d48"
down_revision: str | None = "69091c1537d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Create enum types explicitly (ORM uses create_type=False)
    op.execute(
        "CREATE TYPE booking_status AS ENUM ("
        "'pending','confirmed','cancelled_by_client','cancelled_by_admin',"
        "'completed','no_show','rescheduled')"
    )
    op.execute("CREATE TYPE booking_source AS ENUM ('mini_app','bot','admin_manual')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("business_id", sa.BigInteger(), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("staff_id", sa.BigInteger(), nullable=False),
        sa.Column("service_id", sa.BigInteger(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "confirmed",
                "cancelled_by_client",
                "cancelled_by_admin",
                "completed",
                "no_show",
                "rescheduled",
                name="booking_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("client_comment", sa.Text(), nullable=True),
        sa.Column("admin_comment", sa.Text(), nullable=True),
        sa.Column(
            "source",
            postgresql.ENUM(
                "mini_app", "bot", "admin_manual", name="booking_source", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("ends_at > starts_at", name="ck_bookings_end_after_start"),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["client_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["staff_id"], ["staff_members.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_bookings_client_starts", "bookings", ["client_id", "starts_at"], unique=False
    )
    op.create_index("ix_bookings_staff_starts", "bookings", ["staff_id", "starts_at"], unique=False)
    op.create_index("ix_bookings_status", "bookings", ["status"], unique=False)
    # Partial index for race protection (autogenerate does not emit this)
    op.execute(
        "CREATE INDEX bookings_active_by_staff ON bookings (staff_id, starts_at) "
        "WHERE status IN ('pending', 'confirmed')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS bookings_active_by_staff")
    op.drop_index("ix_bookings_status", table_name="bookings")
    op.drop_index("ix_bookings_staff_starts", table_name="bookings")
    op.drop_index("ix_bookings_client_starts", table_name="bookings")
    op.drop_table("bookings")
    op.execute("DROP TYPE IF EXISTS booking_status")
    op.execute("DROP TYPE IF EXISTS booking_source")
    # ### end Alembic commands ###
